title: Rasidat Yekeen
logo: Rasidat.png
description: Data analyst with 3 years experience analysing data with SQL (for data manipulation and interrogation), PowerBI (for data visualisation).
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
